services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    ports:
      - ${ZOOKEEPER_PORT}:2181

  kafka:
    restart: always
    image: confluentinc/cp-kafka
    hostname: kafka
    links:
     - zookeeper
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST}:${KAFKA_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      ZOOKEEPER_IP: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: 1
      KAFKAJS_NO_PARTITIONER_WARNING: 1

    depends_on:
      - zookeeper
